#!/usr/bin/bash

BLUEJ_FILES="*.bluej bluej.* *.ctxt"

for regex in $BLUEJ_FILES
do
    find . -name $regex
done
read -p "This will delete all the files listed above. Continue? [y/n]" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

for regex in $BLUEJ_FILES 
do
    find . -name $regex -exec rm {} \;
done

echo
echo "You're now free of Bluej ;)"
