#!/usr/bin/bash

FILE="./Program.java"

if [ -f $FILE ]; then
    read -p "File $FILE already exists. Overwrite it? [y/n]" -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi

    echo "" > $FILE
fi


echo "public class Program {" >> $FILE
echo -e "\tpublic static void main(String[] args) {" >> $FILE
echo -e "\t\t// @TODO: implement main method" >> $FILE
echo -e "\t}\n}" >> $FILE

read -p "Your $FILE file is ready. Open current directory with code? [y/n]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    code .
fi

exit 0
