#!/usr/bin/zsh

scrot_dir="$HOME/Pictures/img/screenshots"

[ ! -d "$scrot_dir" ] && mkdir -p "$scrot_dir"

message="Screenshot saved to"

use-scrot () {
    scrot '%Y-%m-%d_$wx$h.png' -e "mv \$f $scrot_dir" $1 $2 $3
}

usage () {
    echo "
Take a screenshot and save it to a file, the clipboard or both.

available options:
-f   | --fullscreen                     full screen
-fc  | --fullscreen-to-clipboard        full screen to clipboard
-fcs | --fullscreen-to-clipboard-save   full screen to clipboard and to a file
-s   | --select                         selection
-sc  | --select-to-clipboard            selection to clipboard
-scs | --select-to-clipboard-save       selection to clipboard and to a file
-h   | --help                           display this information

files are saved to $scrot_dir
"
}

case "$1" in
    --fullscreen|-f)
		use-scrot &&
		sleep 1 &&
        notify-send "$message $scrot_dir"
		;;
    --fullscreen-to-clipboard|-fc)
        cd $scrot_dir
        use-scrot -e 'xclip -selection clipboard -t image/png < $f && rm $f' &&
		sleep 1 && 
        notify-send "Screenshot copied to the clipboard"
		;;
    --fullscreen-to-clipboard-save|-fcs)
        cd $scrot_dir
        use-scrot -e 'xclip -selection clipboard -t image/png < $f' &&
		sleep 1 && 
        notify-send "$message $scrot_dir and copied to the clipboard"
		;;
    --select|-s)
        use-scrot -s && 
		sleep 1 && 
        notify-send "$message $scrot_dir"
		;;
    --select-to-clipboard|-sc)
        cd $scrot_dir
        use-scrot -s -e 'xclip -selection clipboard -t image/png < $f && rm $f' && 
		sleep 1 && 
        notify-send "Screenshot copied to the clipboard"
		;;
    --select-to-clipboard-save|-scs)
        cd $scrot_dir
        use-scrot -s -e 'xclip -selection clipboard -t image/png < $f' &&
		sleep 1 && 
        notify-send "$message $scrot_dir and copied to the clipboard"
		;;
    --help|-h|*)
        usage
        ;;
esac

exit 0
