#!/usr/bin/bash

# Inits JUnit in the current directory by copying
# the files in the $JUNIT_HOME directory (junit
# and hamcrest jar files) into a lib directory
# in the current folder

if ! [ -d $JUNIT_HOME ];
then
    echo "Error: JUNIT_HOME not found, or is not a directory"
    exit 1
fi

if ! [ -d ./lib ];
then
    mkdir ./lib
fi

cp $JUNIT_HOME/* ./lib/
