#!/usr/bin/zsh

if [[ ! $TMUX_SESSION_NAME ]];
then
    echo "Tmux session name env variable not set"
    exit 1
fi

WINDOW="home"
T="$TMUX_SESSION_NAME:$WINDOW"

tmux has-session -t "$T" 2> /dev/null \
    && tmux select-window -t "$T" \
    || tmux new-window -n "$WINDOW"

tmux split-window -h
tmux send-keys -t "$T.0" "cd ~/Documents/code && clear" Enter
tmux send-keys -t "$T.1" "cd ~/.config/ && rr" Enter
tmux split-window -v
sleep 0.5
tmux send-keys -t "$T.2" "cd ~/Documents/code/linux-utils && cmatrix" Enter
sleep 0.5
tmux select-pane -t "$T.0"
