#!/usr/bin/zsh

if [[ ! $TMUX_SESSION_NAME ]];
then
    echo "Tmux session name env variable not set"
    exit 1
fi

WINDOW="home"
T="$TMUX_SESSION_NAME:$WINDOW"

tmux has-session -t "$T" 2> /dev/null \
    && tmux select-window -t "$T" \
    || tmux new-window -n "$WINDOW"

tmux split-window -h
tmux send-keys -t "$T.0" "cd ~/Documents/code" Enter C-l
tmux send-keys -t "$T.1" C-l
tmux split-window -v
sleep 1
tmux send-keys -t "$T.2" C-l
tmux select-pane -t "$T.0"
