#!/usr/bin/bash

# Script for copying all my desired configuration files
# to the folder where I upload to my git repository
#
# @author Dahan Schuster

[ -z $FILES_HOME ] && FILES_HOME=( ".vimrc" ".zshrc" ".tmux.conf" )
[ -z $FILES_CONFIG ] && FILES_CONFIG=( "^i3$" "^rofi$" "^polybar$" "^compton$" "^BetterDiscord$" "^spicetify$")


usage () {
  echo "
Make a copy of all the files listed in \$FILES_HOME and \$FILES_CONFIG that exists
in the \$HOME and \$HOME/.config directories, respectivelly

usage:
update-dotfiles [-d] [-h]

available options:

Only one option can be used per time!

-d | --debug  doesn't make any changes, just print to stdout exactly what will be copied
-h | --help   print this help message and exit 
"
  exit 0
}

debug=0
case "$1" in
  --debug|-d)
    debug=1
    ;;
  --help|-h)
    usage
    ;;
esac

export debug

handlecp() {
  if [ $debug = 1 ]; then
    echo "$2/$1 -> $HOME/c/dotfiles/$3"
  else
    cp -RL "$2/$1" "$HOME/c/dotfiles/$3"
  fi
}

export -f handlecp

cp-to-dotfiles() {
  ls -a $1 | grep "$2" | xargs -I {} /usr/bin/bash -c "handlecp {} $1 $3"
}

# cp $file from $HOME to dotfiles folder 
for file in "${FILES_HOME[@]}"; do
  cp-to-dotfiles $HOME $file
done

# cp $file from $HOME/.config to dotfiles/.config folder 
for file in "${FILES_CONFIG[@]}"; do
  cp-to-dotfiles "$HOME/.config" $file .config 
done
