#!/usr/bin/bash

# Script for copying all my desired configuration files
# to the folder where I upload to my git repository
#
# @author Dahan Schuster

FILES_HOME=( ".vimrc" ".zshrc" ".tmux.conf" )
FILES_CONFIG=( "^i3$" "^rofi$" "^polybar$" )

[ "$1" = '-d' ] && debug=1 || debug=0
export debug

handlecp() {
  if [ $debug = 1 ]; then
    echo "$2/$1 -> $HOME/c/dotfiles/$3"
  else
    cp -RL "$2/$1" "$HOME/c/dotfiles/$3"
  fi
}

export -f handlecp

cp-to-dotfiles() {
  ls -a $1 | grep "$2" | xargs -I {} /usr/bin/bash -c "handlecp {} $1 $3"
}

# cp $file from $HOME to dotfiles folder 
for file in "${FILES_HOME[@]}"; do
  cp-to-dotfiles $HOME $file
done

# cp $file from $HOME/.config to dotfiles/.config folder 
for file in "${FILES_CONFIG[@]}"; do
  cp-to-dotfiles "$HOME/.config" $file .config 
done
